MEETINGS = [
    {
        "title": "Q1 Kickoff — Project Atlas",
        "date": "2026-01-06",
        "project": "Project Atlas",
        "attendees": ["Ahmed", "Sara", "Omar", "Lina", "Yousef"],
        "segments": [
            {"speaker": "Sara", "text": "Welcome back everyone. Project Atlas is our number one priority for the year: a unified customer data platform replacing the three legacy systems."},
            {"speaker": "Ahmed", "text": "The biggest open question is the database layer. We shortlisted PostgreSQL and MySQL last quarter but never closed it."},
            {"speaker": "Lina", "text": "From the data team's side, PostgreSQL wins on JSONB support and partitioning. Our event tables will pass two billion rows within a year."},
            {"speaker": "Omar", "text": "Agreed. Logical replication in PostgreSQL also makes the zero-downtime migration story much cleaner."},
            {"speaker": "Sara", "text": "Then it's settled — we've decided to build Atlas on PostgreSQL instead of MySQL."},
            {"speaker": "Yousef", "text": "If we're on PostgreSQL, we should evaluate Azure Database for PostgreSQL Flexible Server rather than self-hosting. It would fold neatly into the wider Azure migration."},
            {"speaker": "Sara", "text": "Good point. Ahmed, can you own the hosting evaluation?"},
            {"speaker": "Ahmed", "text": "Yes. I'll deliver the managed database vendor comparison report by January 23."},
            {"speaker": "Sara", "text": "Perfect. Lina, what do you need to start the schema work?"},
            {"speaker": "Lina", "text": "Access to the legacy CRM exports. I'll prepare the source data audit by January 30."},
            {"speaker": "Sara", "text": "Let's reconvene weekly. Thanks all."},
        ],
    },
    {
        "title": "Azure Migration Planning",
        "date": "2026-01-13",
        "project": "Azure Migration",
        "attendees": ["Ahmed", "Yousef", "Omar", "Khalid"],
        "segments": [
            {"speaker": "Yousef", "text": "Goal for today: agree the landing zone design for the Azure migration and sequence the workloads."},
            {"speaker": "Omar", "text": "The API gateway and the reporting services are the least entangled. I'd move those first."},
            {"speaker": "Yousef", "text": "Same conclusion here. We agreed to structure the Azure landing zone as hub-and-spoke with a dedicated connectivity subscription."},
            {"speaker": "Khalid", "text": "Finance needs cost visibility from day one. Please tag every resource group by cost center or the monthly reconciliation becomes impossible."},
            {"speaker": "Yousef", "text": "Understood. Tagging policy will be enforced through Azure Policy at the management group level."},
            {"speaker": "Ahmed", "text": "Identity is the other blocker. Single sign-on has to work before anything customer-facing moves."},
            {"speaker": "Ahmed", "text": "I'll finish the SSO integration spec by February 6, covering Entra ID and the fallback flows."},
            {"speaker": "Omar", "text": "I'll map the service dependency graph by January 27 so we can order the migration waves properly."},
            {"speaker": "Yousef", "text": "Great. Next checkpoint in two weeks."},
        ],
    },
    {
        "title": "Atlas Data Model Review",
        "date": "2026-01-20",
        "project": "Project Atlas",
        "attendees": ["Ahmed", "Lina", "Omar", "Noor"],
        "segments": [
            {"speaker": "Lina", "text": "Draft schema is ready. Core entities: customer, account, consent, interaction, and a unified event stream."},
            {"speaker": "Omar", "text": "How do we handle schema evolution once pilot customers are live?"},
            {"speaker": "Lina", "text": "Migrations as code. Every change reviewed and versioned."},
            {"speaker": "Ahmed", "text": "Let's make that formal — we agreed to version every schema change through Flyway migrations with mandatory review."},
            {"speaker": "Noor", "text": "For QA I need seeded anonymized data. Can we generate synthetic customers from the legacy distributions?"},
            {"speaker": "Lina", "text": "Yes. I'll build the synthetic data generator by February 20."},
            {"speaker": "Noor", "text": "Then I can draft acceptance tests against it. I'll write the Atlas acceptance test plan by March 13."},
            {"speaker": "Ahmed", "text": "Good session. Schema freeze target is end of February."},
        ],
    },
    {
        "title": "Weekly Sync — Atlas & Azure",
        "date": "2026-01-27",
        "project": "Project Atlas",
        "attendees": ["Ahmed", "Sara", "Omar", "Lina", "Yousef"],
        "segments": [
            {"speaker": "Ahmed", "text": "Quick update from me first. I've delivered the managed database vendor comparison report — it's on the shared drive."},
            {"speaker": "Ahmed", "text": "Bottom line: Azure Database for PostgreSQL comes out ahead on failover SLA and cost at our scale, versus AWS RDS and self-hosting."},
            {"speaker": "Sara", "text": "Nice work. That strengthens the case for consolidating on Azure."},
            {"speaker": "Omar", "text": "I finished the service dependency graph as well. Twenty-three services, four migration waves. The reporting stack is wave one."},
            {"speaker": "Yousef", "text": "I'll stand up the Azure connectivity subscription and hub network by February 13."},
            {"speaker": "Lina", "text": "Source data audit is nearly done, one legacy CRM export is still corrupted. Chasing the vendor."},
            {"speaker": "Sara", "text": "Flag it early if it slips. Anything else? Good, short one today."},
        ],
    },
    {
        "title": "Phoenix Mobile App Kickoff",
        "date": "2026-02-10",
        "project": "Phoenix Mobile",
        "attendees": ["Sara", "Mariam", "Omar", "Noor", "Khalid"],
        "segments": [
            {"speaker": "Sara", "text": "Phoenix is the customer-facing counterpart to Atlas — a mobile app giving customers self-service over their own data."},
            {"speaker": "Mariam", "text": "Design direction: one codebase, native feel. We evaluated Flutter and React Native over the past month."},
            {"speaker": "Omar", "text": "The team has deeper TypeScript experience, and we can share validation logic with the web app."},
            {"speaker": "Sara", "text": "Then we're going with React Native for Phoenix."},
            {"speaker": "Mariam", "text": "I'll have the design system and component library ready by March 6."},
            {"speaker": "Khalid", "text": "What's the budget envelope? App store fees, device lab, push infrastructure — I need numbers before end of quarter."},
            {"speaker": "Omar", "text": "I'll draft the Phoenix infrastructure cost estimate by February 27."},
            {"speaker": "Noor", "text": "Device coverage matters more than people think. We should test on the ten most common devices in our market, not just flagships."},
            {"speaker": "Sara", "text": "Agreed. Kickoff done — first sprint starts Monday."},
        ],
    },
    {
        "title": "Azure Cost Review",
        "date": "2026-02-17",
        "project": "Azure Migration",
        "attendees": ["Khalid", "Yousef", "Ahmed", "Sara"],
        "segments": [
            {"speaker": "Khalid", "text": "First month of Azure spend is in. Dev and staging together are tracking eighteen percent over the estimate."},
            {"speaker": "Yousef", "text": "Most of that is oversized dev VMs left running overnight. Auto-shutdown policies will fix it. Separately, I finished the connectivity subscription and hub network build-out last week."},
            {"speaker": "Khalid", "text": "For production we should not pay on-demand rates. Reserved capacity is thirty to forty percent cheaper for steady workloads."},
            {"speaker": "Sara", "text": "Fine — we're going with three-year reserved instances for the production database cluster."},
            {"speaker": "Yousef", "text": "I'll apply the auto-shutdown policy to all non-production Azure subscriptions by February 24."},
            {"speaker": "Ahmed", "text": "On identity: I've completed the SSO integration spec and shared it with the security group."},
            {"speaker": "Sara", "text": "Saw it, good document. Let's keep monthly cost reviews going forward."},
        ],
    },
    {
        "title": "Atlas Sprint Review",
        "date": "2026-02-24",
        "project": "Project Atlas",
        "attendees": ["Ahmed", "Lina", "Omar", "Noor"],
        "segments": [
            {"speaker": "Lina", "text": "I've completed the synthetic data generator and published the source data audit. The corrupted CRM export finally came through clean."},
            {"speaker": "Omar", "text": "Ingestion pipeline handles the full historical load in under four hours. Deduplication logic is next."},
            {"speaker": "Ahmed", "text": "Schema freeze holds for Friday then. Anything blocking QA?"},
            {"speaker": "Noor", "text": "No blockers. Acceptance test plan is half drafted, still on for March 13."},
            {"speaker": "Omar", "text": "One risk: the consent model changed twice this sprint. If legal changes it again after freeze, that's a migration."},
            {"speaker": "Ahmed", "text": "I'll get written sign-off from legal on the consent model by March 6."},
            {"speaker": "Lina", "text": "Please do — every consent change costs us a week."},
        ],
    },
    {
        "title": "Security & Compliance Review",
        "date": "2026-03-10",
        "project": "Azure Migration",
        "attendees": ["Sara", "Ahmed", "Omar", "Yousef", "Noor"],
        "segments": [
            {"speaker": "Sara", "text": "Two topics: the compliance target for the year, and the penetration test results."},
            {"speaker": "Ahmed", "text": "Enterprise prospects keep asking for SOC 2. Without it we're locked out of two active deals."},
            {"speaker": "Sara", "text": "Then it's clear — we decided to adopt SOC 2 Type II as the compliance target for this year."},
            {"speaker": "Yousef", "text": "The pen test found eleven issues: two high, four medium, five low. The high ones are an exposed staging endpoint and an over-privileged service account."},
            {"speaker": "Omar", "text": "The service account one is mine. I'll remediate the high and medium pen test findings by April 24."},
            {"speaker": "Noor", "text": "I'd like retesting scheduled right after, not at year end."},
            {"speaker": "Yousef", "text": "Agreed, I'll book the retest window with the vendor for early May."},
            {"speaker": "Sara", "text": "Ahmed, add SOC 2 evidence collection to the Atlas workplan — auditors will want six months of logs."},
        ],
    },
    {
        "title": "Atlas Pilot Readiness",
        "date": "2026-03-24",
        "project": "Project Atlas",
        "attendees": ["Ahmed", "Sara", "Lina", "Omar", "Noor", "Yousef"],
        "segments": [
            {"speaker": "Ahmed", "text": "Pilot question: big bang or phased? Sales wants all five pilot customers at once."},
            {"speaker": "Lina", "text": "Phased. The analytics module is self-contained and read-only — lowest risk surface."},
            {"speaker": "Omar", "text": "Plus a phased start gives us real load data before the write paths go live."},
            {"speaker": "Sara", "text": "Let's go with a phased rollout starting with the analytics module."},
            {"speaker": "Ahmed", "text": "Then I'll onboard the first three pilot customers by April 10."},
            {"speaker": "Noor", "text": "I've finished the Atlas acceptance test plan and the tests are green on synthetic data. I want one full rehearsal on a production-like environment before any real customer touches it."},
            {"speaker": "Yousef", "text": "You'll have it — staging on Azure mirrors production topology since last week."},
            {"speaker": "Ahmed", "text": "One more update — I've closed out the legal sign-off on the consent model, we have it in writing."},
            {"speaker": "Sara", "text": "Good milestone, everyone. Pilot week starts now."},
        ],
    },
    {
        "title": "Azure Migration Checkpoint",
        "date": "2026-04-07",
        "project": "Azure Migration",
        "attendees": ["Yousef", "Ahmed", "Omar", "Khalid"],
        "segments": [
            {"speaker": "Yousef", "text": "Waves one and two are fully migrated to Azure — reporting stack and the API gateway. Zero customer-visible downtime."},
            {"speaker": "Khalid", "text": "And the cost line is finally under estimate. Auto-shutdown alone cut non-production spend by a quarter."},
            {"speaker": "Yousef", "text": "Wave three is the big one: the primary databases. I'll complete the staging environment cutover by April 17 as the dress rehearsal."},
            {"speaker": "Omar", "text": "Dependency graph says wave three needs the message queue moved first. That's a two-day job, already scheduled."},
            {"speaker": "Ahmed", "text": "Any risk to the Atlas pilot dates from wave three?"},
            {"speaker": "Yousef", "text": "No — pilot runs on the new Azure environment already, it's the legacy systems that are moving."},
            {"speaker": "Khalid", "text": "Keep receipts for everything, the reserved instance true-up is in June."},
        ],
    },
    {
        "title": "Weekly Sync — Pilot Week",
        "date": "2026-04-14",
        "project": "Project Atlas",
        "attendees": ["Ahmed", "Sara", "Lina", "Noor"],
        "segments": [
            {"speaker": "Ahmed", "text": "Milestone update: I've completed onboarding the first three pilot customers — Meridian, Corvex, and Halcyon Retail are live on the analytics module."},
            {"speaker": "Sara", "text": "Excellent. Early feedback?"},
            {"speaker": "Ahmed", "text": "Meridian loves the dashboard latency. Corvex hit one CSV export bug, already patched."},
            {"speaker": "Noor", "text": "The rehearsal paid off — the export bug was the only escape, and it was cosmetic."},
            {"speaker": "Lina", "text": "Data quality metrics look strong: match rate on identity resolution is ninety-eight point six percent."},
            {"speaker": "Sara", "text": "Let's decide the remaining pilot schedule next week once we have seven days of runtime data."},
        ],
    },
    {
        "title": "Atlas GA Planning",
        "date": "2026-05-05",
        "project": "Project Atlas",
        "attendees": ["Sara", "Ahmed", "Lina", "Omar", "Khalid", "Mariam"],
        "segments": [
            {"speaker": "Sara", "text": "Pilot has been stable for three weeks. Time to talk general availability."},
            {"speaker": "Ahmed", "text": "Remaining scope: write paths, the consent portal, and billing integration. Realistically that's July for feature-complete."},
            {"speaker": "Sara", "text": "Then we agreed to target September 15 for Atlas general availability, with feature freeze on August 3."},
            {"speaker": "Khalid", "text": "Pricing needs to land well before that. We're going with usage-based pricing tiered by monthly tracked profiles."},
            {"speaker": "Lina", "text": "Migration tooling is the hidden workload — every GA customer arrives with legacy data. I'll publish the data migration runbook by June 5."},
            {"speaker": "Omar", "text": "Write path performance testing starts next sprint. Target is five thousand writes per second sustained."},
            {"speaker": "Mariam", "text": "The consent portal needs design time too — it's customer-facing and legally sensitive. I'll deliver the consent portal designs by June 1."},
            {"speaker": "Sara", "text": "Great. September 15. Put it everywhere."},
        ],
    },
    {
        "title": "Phoenix Beta Review",
        "date": "2026-05-19",
        "project": "Phoenix Mobile",
        "attendees": ["Mariam", "Omar", "Noor", "Sara"],
        "segments": [
            {"speaker": "Mariam", "text": "I've delivered the design system and component library — forty-two components, dark mode included, all documented in Storybook."},
            {"speaker": "Omar", "text": "Beta build is on TestFlight and the Play internal track. Crash-free rate is ninety-nine point two percent. I also delivered the Phoenix infrastructure cost estimate to Khalid back in March."},
            {"speaker": "Noor", "text": "Coverage is the gap. I'll build the automated regression suite for the ten target devices by June 12."},
            {"speaker": "Sara", "text": "Beta feedback themes?"},
            {"speaker": "Mariam", "text": "Biometric login is the most requested feature, then offline mode. Both are on the backlog."},
            {"speaker": "Sara", "text": "Decision: biometric login goes into the launch scope, offline mode waits for version 1.1."},
            {"speaker": "Omar", "text": "Reasonable — biometrics is a week, offline sync is a quarter."},
        ],
    },
    {
        "title": "Azure Production Cutover Review",
        "date": "2026-06-02",
        "project": "Azure Migration",
        "attendees": ["Yousef", "Ahmed", "Sara", "Omar", "Khalid"],
        "segments": [
            {"speaker": "Yousef", "text": "I've completed the staging environment cutover and the production wave three cutover both — primary databases now run on Azure Database for PostgreSQL."},
            {"speaker": "Yousef", "text": "Total downtime was four minutes, inside the maintenance window. Replication lag never exceeded two seconds."},
            {"speaker": "Sara", "text": "That's the hardest wave done. Congratulations."},
            {"speaker": "Omar", "text": "One follow-up: global customers report slow asset loads from other regions. We need a CDN and smarter routing."},
            {"speaker": "Yousef", "text": "Evaluated three options — we're going with Azure Front Door for global routing and CDN."},
            {"speaker": "Ahmed", "text": "With production on new infrastructure, the on-call runbooks are stale. I'll draft the incident response playbook by June 26."},
            {"speaker": "Khalid", "text": "Reserved instance true-up numbers came in, we're four percent under budget for the half."},
            {"speaker": "Sara", "text": "Wave four, the long tail of internal tools, can go at its own pace. Main migration is effectively done."},
        ],
    },
    {
        "title": "Mid-Year Review",
        "date": "2026-06-16",
        "project": "Company",
        "attendees": ["Sara", "Ahmed", "Khalid", "Mariam", "Yousef", "Lina"],
        "segments": [
            {"speaker": "Sara", "text": "Half-year scorecard: Atlas pilot live, Azure migration ninety percent complete, Phoenix in beta. Strong first half."},
            {"speaker": "Khalid", "text": "Financially we're three percent under budget overall. The Azure reserved instances and shutdown policies made the difference."},
            {"speaker": "Sara", "text": "For the second half — we decided to concentrate hiring on two roles: a senior data engineer for Atlas and a mobile engineer for Phoenix."},
            {"speaker": "Ahmed", "text": "The SOC 2 audit window opens in October. Evidence collection is running but the incident response playbook is still on my plate."},
            {"speaker": "Mariam", "text": "I delivered the consent portal designs on schedule, as promised. Development started last week."},
            {"speaker": "Lina", "text": "I need to flag that the data migration runbook slipped — the write path changes keep invalidating it. New estimate is mid-July."},
            {"speaker": "Sara", "text": "Noted. It's on the GA critical path, so keep it visible. Same for the regression suite, Noor is stretched."},
        ],
    },
    {
        "title": "Weekly Sync — GA Runway",
        "date": "2026-07-06",
        "project": "Project Atlas",
        "attendees": ["Ahmed", "Sara", "Lina", "Omar", "Noor"],
        "segments": [
            {"speaker": "Ahmed", "text": "Ten weeks to GA. Feature freeze August 3 — write paths are code complete, consent portal is in review."},
            {"speaker": "Omar", "text": "Performance testing hit five thousand two hundred writes per second sustained. Target met with headroom."},
            {"speaker": "Lina", "text": "Runbook update: write paths are finally stable so the doc is unblocked. I'll publish the data migration runbook by July 17, final answer."},
            {"speaker": "Noor", "text": "Regression suite is my priority this sprint. I'll finish the billing integration test cases by July 31 as well."},
            {"speaker": "Ahmed", "text": "And I owe everyone the incident response playbook — it's half written, this week I clear it."},
            {"speaker": "Sara", "text": "Overdue items get daily standup visibility until they close. Otherwise, strong position for September 15."},
        ],
    },
]
